spring:
  application:
    name: webflux-chat-app

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chatdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20

  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chatdb}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_SECONDS}

server:
  port: 8080

logging:
  level:
    org.chatapp: DEBUG
    org.springframework.r2dbc: DEBUG
